### PR TITLE
feat: fix forge-std lib and update readme

### PR DESCRIPTION
**Pull request by simonbdefi**
* Update `forge-std` module to master (was causing test issues on fresh install)
* Add Node.js in readme requirements
* Improve environment variables section in readme

### CODE REVIEW

**Comment by Schlagonia** [comment]
- can you update the installed forg-std dependency too. Not just to submodule file. That way if people directly fork it will be the correct dependency
- The etherscan API key is not ever actually used. One thing i keep meaning to do is remove it all togethor. Can you delete all reference to ETHERSCAN_API_KEY including the env example, the Make file and the read me?

**Comment by simonbdefi** [comment]
@Schlagonia added in https://github.com/yearn/tokenized-strategy-foundry-mix/pull/31/commits/0d4516842e6d3e499c8db152dcff9c9414b485e9 , for your review please

**Comment by Schlagonia** [comment]
just merged a PR on the periphery repo. Since this is already open. Can you also just update the periphery dependency to the latest commit on the master branch.

Should just be an update to BaseHealthCheck. commit: bbc3a0354f45dab087a4c82650e42225433c8fef

**Comment by simonbdefi** [comment]
periphery lib updated

**Review by Schlagonia — APPROVED** [review]

**Pull request merged**
